from typing import Protocol

class AuthService(Protocol):
    def verify_password(self, plain: str, hashed: str) -> bool: ...
    def hash_password(self, plain: str) -> str: ...
    def create_access_token(self, sub: str) -> str: ...
