from typing import Optional, Sequence, Protocol
from uuid import UUID
from app.domain.user import User

class UserRepository(Protocol):
    def get_by_id(self, user_id: UUID) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def list(self, offset: int, limit: int) -> Sequence[User]: ...
    def count(self) -> int: ...
    def add(self, user: User) -> None: ...
    def update(self, user: User) -> None: ...
    def delete(self, user_id: UUID) -> None: ...
