name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps via npm (pip inside)
        run: npm install
      - name: Run tests
        run: npm test
